"use client";

import { useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import styles from "./InterviewQA.module.css";

type Question = { id: string; category: string; difficulty: "Foundation" | "Working knowledge" | "Senior"; question: string; short: string; detail: string; asked: string; mistakes: string; example: string; followUps: string[]; related: string[] };
const topics = [["javascript", "JavaScript"], ["react", "React"], ["next", "Next.js"], ["typescript", "TypeScript"], ["api", "APIs"]] as const;
const questions: Question[] = [
  { id:"closure", category:"javascript", difficulty:"Working knowledge", question:"What is a closure, and where can it surprise you?", short:"A function retains access to the lexical scope where it was created, not where it is called.", detail:"Closures are the mechanism behind callbacks, module-private state, and many React handlers. They become a problem when a callback outlives the values you expected it to see. The bug is rarely that a closure exists; it is that its lifetime was not designed.", asked:"Frontend screens, JavaScript fundamentals, debugging rounds.", mistakes:"Saying closures are only for data hiding, or claiming they copy values at function creation time.", example:"A click handler scheduled with setTimeout can still read an earlier state value. In React, use functional updates or keep the latest mutable value in a ref when that is the contract.", followUps:["How do closures interact with loops?", "How do stale closures appear in hooks?"], related:["Lexical scope", "Event loop", "useRef"] },
  { id:"eventloop", category:"javascript", difficulty:"Senior", question:"How do tasks and microtasks change the order of async code?", short:"After the current stack clears, JavaScript drains microtasks before it takes the next task.", detail:"Promise reactions and queueMicrotask run in the microtask queue; timers and UI events are tasks. A long chain of microtasks can delay rendering just as effectively as a long synchronous loop. Knowing that ordering matters when coordinating loading states, teardown, and tests.", asked:"Frontend architecture and asynchronous debugging interviews.", mistakes:"Calling every callback a 'thread', or describing setTimeout as a precise timer.", example:"If a promise callback queues another promise callback, both run before a pending setTimeout callback. Use that fact sparingly; application sequencing should still be explicit.", followUps:["What is requestAnimationFrame for?", "Can microtasks starve rendering?"], related:["Promises", "queueMicrotask", "Rendering"] },
  { id:"render", category:"react", difficulty:"Working knowledge", question:"What causes a React component to render again?", short:"Its state changes, its parent renders, a consumed context value changes, or an external store subscription signals an update.", detail:"A render is React calculating the next UI, not necessarily changing the DOM. Memoization is useful when a measured expensive subtree receives stable inputs; it is not a default response to every render. Most performance issues start with state placed too high in the tree or expensive work in render.", asked:"React implementation and performance conversations.", mistakes:"Saying React only rerenders when props change, or treating React.memo as a guarantee of no rerenders.", example:"Move a search input and its state next to the results that need it instead of keeping it in a top-level shell. Fewer unrelated branches become eligible to render.", followUps:["When does React.memo help?", "What is referential equality?"], related:["State colocation", "useMemo", "React DevTools profiler"] },
  { id:"effect", category:"react", difficulty:"Senior", question:"When should you use an effect instead of an event handler?", short:"Use an event handler for work caused by a user action; use an effect to synchronize with something outside React after render.", detail:"An effect is appropriate for subscriptions, browser APIs, and keeping an external system aligned with rendered state. If the work happens because the user pressed Save, run it in the Save handler. Effects used as a second event system create duplicate calls and awkward dependency fixes.", asked:"Senior frontend and code-review interviews.", mistakes:"Treating useEffect as a lifecycle bucket or removing dependencies to silence the linter.", example:"Send analytics for a completed purchase in the purchase flow, not in an effect watching a 'purchased' boolean. Subscribe to a WebSocket channel in an effect because that channel follows the rendered view.", followUps:["Why must an effect return cleanup?", "How do you avoid stale requests?"], related:["Effect cleanup", "AbortController", "Dependencies"] },
  { id:"server-client", category:"next", difficulty:"Working knowledge", question:"How do you decide between a Server and Client Component?", short:"Start on the server; add a client boundary only where state, browser APIs, or event handlers are needed.", detail:"Server Components keep data access and heavy dependencies off the browser bundle. Client Components are for interaction. The important unit is the boundary: placing it high makes everything below it client JavaScript, even if most of the tree is static.", asked:"Next.js system-design and bundle-performance interviews.", mistakes:"Putting 'use client' on a layout for one interactive button, or assuming a Client Component cannot receive server-rendered children.", example:"Render a product page and its data on the server, then pass the rendered description and a small quantity picker into a client component. The picker hydrates; the document-like content does not need to.", followUps:["What crosses the RSC boundary?", "How do you keep a client bundle small?"], related:["RSC", "Hydration", "Code splitting"] },
  { id:"narrowing", category:"typescript", difficulty:"Foundation", question:"Why is unknown safer than any at an API boundary?", short:"unknown forces validation before use; any turns off the type checker exactly where untrusted data needs it most.", detail:"Values from JSON, storage, URL parameters, and third-party libraries are runtime facts, not TypeScript facts. Start with unknown, validate shape, then narrow. It makes an incorrect assumption visible close to its source instead of becoming a distant runtime failure.", asked:"TypeScript fundamentals and API integration rounds.", mistakes:"Using a type assertion as validation, or assuming JSON.parse returns the declared type.", example:"Check that a response has a string id before passing it into application code. A schema library can help at large boundaries, but a type guard is often enough for a small one.", followUps:["What is a user-defined type guard?", "When is any acceptable?"], related:["Type guards", "Discriminated unions", "Runtime validation"] },
  { id:"idempotency", category:"api", difficulty:"Senior", question:"What does idempotency mean for an API write?", short:"Repeating the same intended request has the same observable outcome as sending it once.", detail:"Retries are normal: mobile networks drop responses, browsers resubmit, and queues redeliver. A payment or order endpoint needs an idempotency key bound to the caller and request payload, then it should return the original result for a matching retry.", asked:"Backend, payments, and distributed-systems interviews.", mistakes:"Equating idempotency with 'no side effects', or trusting a client-side disabled button as duplicate protection.", example:"Store the key and completed response in the same transactional boundary as the order. If the same key arrives with a different payload, reject it rather than silently reusing the result.", followUps:["Where do you store the key?", "How long should keys live?"], related:["HTTP retries", "Transactions", "Exactly-once semantics"] },
];

export default function InterviewQA() {
  const params = useSearchParams(); const queryTopic = params.get("tech")?.toLowerCase();
  const [topic, setTopic] = useState(topics.some(([id]) => id === queryTopic) ? queryTopic! : "javascript");
  const [open, setOpen] = useState(questions[0].id);
  const [query, setQuery] = useState("");
  function selectTopic(nextTopic: string) { setTopic(nextTopic); setOpen(questions.find((item) => item.category === nextTopic)?.id || ""); setQuery(""); }
  const current = useMemo(() => questions.filter((item) => item.category === topic && `${item.question} ${item.short}`.toLowerCase().includes(query.toLowerCase())), [topic, query]);
  return <section className={styles.page} aria-labelledby="qa-title"><header className={styles.hero}><p className={styles.eyebrow}>Interview notes</p><h1 id="qa-title">Know the answer. Explain the trade-off.</h1><p>Practical prompts with enough context to hold up after the first follow-up.</p></header><div className={styles.layout}><aside className={styles.sidebar}><p>Topics</p><nav>{topics.map(([id, label]) => <button key={id} className={topic === id ? styles.selected : ""} onClick={() => selectTopic(id)}><span>{label}</span><small>{questions.filter((q) => q.category === id).length}</small></button>)}</nav><div className={styles.sidebarNote}>Answers are written for discussion, not memorization. Start with the short answer, then add context.</div></aside><main><div className={styles.contentHead}><div><p className={styles.eyebrow}>{topics.find(([id]) => id === topic)?.[1]}</p><h2>Questions to work through</h2></div><label className={styles.search}><span aria-hidden="true">⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filter this topic" aria-label="Filter questions" />{query && <button onClick={() => setQuery("")} aria-label="Clear filter">×</button>}</label></div><div className={styles.list}>{current.map((item, index) => { const expanded = open === item.id; return <article className={`${styles.item} ${expanded ? styles.expanded : ""}`} key={item.id}><button className={styles.question} onClick={() => setOpen(expanded ? "" : item.id)} aria-expanded={expanded}><span className={styles.number}>{String(index + 1).padStart(2,"0")}</span><span><em className={styles.level}>{item.difficulty}</em><strong>{item.question}</strong><b>{item.short}</b></span><i aria-hidden="true">⌄</i></button>{expanded && <div className={styles.answer}><section><h3>Detailed explanation</h3><p>{item.detail}</p></section><div className={styles.answerGrid}><section><h3>Where it comes up</h3><p>{item.asked}</p></section><section><h3>Common mistake</h3><p>{item.mistakes}</p></section></div><section className={styles.example}><h3>Production example</h3><p>{item.example}</p></section><footer><div><span>Follow-up prompts</span>{item.followUps.map((followUp) => <button key={followUp} onClick={() => setQuery(followUp)}>{followUp}</button>)}</div><p>Related: {item.related.join(" · ")}</p></footer></div>}</article>})}</div>{!current.length && <div className={styles.empty}><strong>No question matches that filter.</strong><button onClick={() => setQuery("")}>Clear filter</button></div>}</main></div></section>;
}
